version: "3"
services:
  server:
    image: andmesz/api-docker:0.2
    networks:
      docker-mysql:
    build: .
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb/api-docker?useSSL=false
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:latest
    networks:
      docker-mysql:
    hostname: mysqldb
    environment:
      - MYSQL_DATABASE=api-docker
      - MYSQL_PASSWORD=12345678
      - MYSQL_ROOT_PASSWORD=12345678
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
        - mysqldb:/var/lib/mysql
volumes:
  mysqldb:

networks:
  docker-mysql: